### ISSUE TITLE
Popover shortcut no longer working following upgrade to v0.11

### ISSUE THREAD

**Issue by cstace** [adur1990/Pass-for-macOS#44]
## Describe the bug
Popover shortcut no longer working after updating to v0.11.

## To Reproduce
Update Pass for MacOS to v0.11.

## Expected behavior
Expected the popover to work as previously.

## Desktop (please complete the following information)
 - macOS version: 11.1
 - Safari version: 14.0.2
 - Passafari version: 0.11
 - How was Passafari installed (Github release, built self, ...): Homebrew

## Additional information
The popover shortcut now triggers the menu in the same way that ctrl-clicking the menubar icon does. It no longer reveals the popover menu. Downgrading to v0.10 does not change this behaviour.

**Comment by adur1990** [comment]
Thank you for reporting this issue.
Unfortunately, I can not reproduce this. Heres is the behavior I have, which is also completely intended:

### Host app
* `left-click` on the status bar item opens the popover for password search.
* Using the shortcut (`shift-ctrl-p` by default or changed by the user) opens the popover for password search, if no Safari window is in foreground.
* `right-click` on the status bar item opens the context menu with version information, preferences button, etc.
* `ctrl-click` on the status bar item opens the context menu with version information, preferences button, etc.

### Safari Extension
* `left-click` on the Safari extension item opens the popover for searching passwords, which is pre-filled with the current domain.
* `right-click` on the Safari extension has no functionality.
* `ctrl-click` on the Safari extension has no functionality.
* Using the shortcut (`shift-ctrl-p` by default or changed by the user) if Safari is in foreground will search for passwords for the current domain. If only one is found, it will be auto-filled. If more than one matching password is found, the popover in Safari will open to either refine the search or select the correct password.

Could you elaborate on your problem and try to be more specific about how this came about? Otherwise, I can't help you.

**Comment by Msouza91** [comment]
I can confirm, on Big Sur 11.2, pass for macOS 0.11, Ctrl+Click works as intended, but the keyboard shortcut is opening the right click menu.

**Comment by adur1990** [comment]
This is really strange. I can not see any reason for this. Can you try to change the shortcut in the preferences? Does it fix anything? If it does, try to change it back to the shortcut you use.

**Comment by Msouza91** [comment]
I had to send the mac for repair and github didn't notify me from your reply. As soon as I get it back I'll check, unfortunately they had to restore the OS so the issue may not reproduce in the new installation, but an update will be posted shortly.

**Comment by adur1990** [comment]
Thanks for the update.
I hope you will get your machine back soon.

**Comment by AnotherProksY** [comment]
The same problem here. But the proposed option with replacing the shortcut fixed the error!

**Comment by adur1990** [comment]
That's really weird. Can you change the shortcut back without the problem coming up again?

**Comment by adur1990** [comment]
Oh dear, I found the bug. I will fix it asap and give more details about what happened.

**Comment by adur1990** [comment]
Unfortunately, the code for `ctrl-click` was only checking if `ctrl` was pressed, but not if `left-click` was used at the same time. This resulted in the problem that the context menu was opened instead of the popover if the shortcut contained `ctrl`.

**Comment by Msouza91** [comment]
Hello, got the mac bac yesterday, installed pass4mOS through brew cask this time to see if it would make any difference, changed the shortcut back and forth, but no dice.

**Comment by adur1990** [comment]
@Msouza91 This issue should be fixed in v0.11.1.
